version: 2.1

# Environment to run job
executors:
  # In this case using docker with a stable version
  docker:
    docker:
      - image: docker:stable

#  Define several jobs to be executed
jobs:
  # Define a job named lint-dockerfile, which is used to lint the dockerfile
  lint-dockerfile:
    # Using docker as executor
    executor: docker
    # Define some steps of lint-dockerfile job
    steps:
      # Checkout from project's code
      - checkout
      # Configure a remote docker environment to for building and testing with docker
      - setup_remote_docker
      # Run the Hadolint Docker Image on the Dockerfile
      - run:
          name: Linting Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  # Define a job named 'test-app' which is used to run unit test
  test-app:
    # Using image cimg/go:1.15 as environment for test-app job
    docker:
      - image: cimg/go:1.15
    # Define some steps of test-app job
    steps:
      # Checkout from project's code
      - checkout
      # Run the command for unit test
      - run:
          name: Run Test App using golang
          command: go test -v -short --count=1 $(go list ./...)
  # Define a job named 'build-app-karsajobs' which is used to push docker image
  build-app-karsajobs:
    # Using docker as executor
    executor: docker
    # Define some steps of 'build-app-karsajobs' job
    steps:
      # Checkout from project's code
      - checkout
      # Configure a remote docker environment to for building and testing with docker
      - setup_remote_docker
      # Run command to execute a script file containing commands to push the docker image to Github Packages
      - run:
          name: Build and Push Image
          command: sh build_push_image_karsajobs.sh

# Sorting the jobs that have been defined
workflows:
  version: 2
  # Define a workflow named 'karsajob-workflow'
  karsajob-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          # This job will be run when the test-app job is success fully
          requires:
            - test-app
